// compliments.js
// 200+ uplifting compliments for CheeryDrop

export const compliments = [
  "You light up the room!",
  "Your positivity is infectious.",
  "You have a great sense of humor!",
  "You are a ray of sunshine.",
  "You make a difference every day.",
  "Your smile is contagious.",
  "You are stronger than you think.",
  "You bring out the best in others.",
  "You are a wonderful friend.",
  "You inspire those around you.",
  "You are a joy to be around!",
  "You have a heart of gold.",
  "You make the world a better place.",
  "You are so thoughtful.",
  "You have a beautiful soul.",
  "You are incredibly creative.",
  "You always know how to cheer people up.",
  "You are a great listener.",
  "You are wise beyond your years.",
  "You have a contagious laugh.",
  "You are a true original.",
  "You are so easy to talk to.",
  "You have a calming presence.",
  "You are a breath of fresh air.",
  "You are a fantastic problem solver.",
  "You are so supportive.",
  "You are a natural leader.",
  "You are so generous.",
  "You are a great role model.",
  "You are always so helpful.",
  "You are a bright spark.",
  "You are so patient.",
  "You are a joy to work with.",
  "You are so reliable.",
  "You are a great storyteller.",
  "You are so resourceful.",
  "You are a true friend.",
  "You are so genuine.",
  "You are a great motivator.",
  "You are so optimistic.",
  "You are a quick learner.",
  "You are so talented.",
  "You are a great cook.",
  "You are so adventurous.",
  "You are a great dancer.",
  "You are so artistic.",
  "You are a great singer.",
  "You are so athletic.",
  "You are a great writer.",
  "You are so musical.",
  "You are a great teacher.",
  "You are so inspiring.",
  "You are a great parent.",
  "You are so brave.",
  "You are a great sibling.",
  "You are so thoughtful.",
  "You are a great child.",
  "You are so loving.",
  "You are a great partner.",
  "You are so kind.",
  "You are a great neighbor.",
  "You are so fun to be around.",
  "You are a great team player.",
  "You are so dependable.",
  "You are a great leader.",
  "You are so encouraging.",
  "You are a great friend.",
  "You are so thoughtful.",
  "You are a great listener.",
  "You are so creative.",
  "You are a great thinker.",
  "You are so smart.",
  "You are a great planner.",
  "You are so organized.",
  "You are a great communicator.",
  "You are so articulate.",
  "You are a great speaker.",
  "You are so persuasive.",
  "You are a great negotiator.",
  "You are so diplomatic.",
  "You are a great mediator.",
  "You are so fair-minded.",
  "You are a great judge of character.",
  "You are so insightful.",
  "You are a great observer.",
  "You are so perceptive.",
  "You are a great analyst.",
  "You are so logical.",
  "You are a great strategist.",
  "You are so visionary.",
  "You are a great dreamer.",
  "You are so imaginative.",
  "You are a great innovator.",
  "You are so inventive.",
  "You are a great creator.",
  "You are so original.",
  "You are a great designer.",
  "You are so stylish.",
  "You are a great decorator.",
  "You are so tasteful.",
  "You are a great host.",
  "You are so welcoming.",
  "You are a great guest.",
  "You are so polite.",
  "You are a great conversationalist.",
  "You are so charming.",
  "You are a great entertainer.",
  "You are so witty.",
  "You are a great comedian.",
  "You are so funny.",
  "You are a great prankster.",
  "You are so playful.",
  "You are a great adventurer.",
  "You are so courageous.",
  "You are a great explorer.",
  "You are so curious.",
  "You are a great learner.",
  "You are so studious.",
  "You are a great researcher.",
  "You are so knowledgeable.",
  "You are a great expert.",
  "You are so skilled.",
  "You are a great craftsman.",
  "You are so handy.",
  "You are a great builder.",
  "You are so constructive.",
  "You are a great fixer.",
  "You are so resourceful.",
  "You are a great helper.",
  "You are so selfless.",
  "You are a great volunteer.",
  "You are so giving.",
  "You are a great philanthropist.",
  "You are so charitable.",
  "You are a great humanitarian.",
  "You are so compassionate.",
  "You are a great caregiver.",
  "You are so nurturing.",
  "You are a great supporter.",
  "You are so loyal.",
  "You are a great companion.",
  "You are so devoted.",
  "You are a great friend to all.",
  "You are so inclusive.",
  "You are a great uniter.",
  "You are so harmonious.",
  "You are a great peacemaker.",
  "You are so calm.",
  "You are a great comforter.",
  "You are so soothing.",
  "You are a great encourager.",
  "You are so uplifting.",
  "You are a great cheerleader.",
  "You are so enthusiastic.",
  "You are a great energizer.",
  "You are so lively.",
  "You are a great spirit.",
  "You are so vibrant.",
  "You are a great inspiration.",
  "You are so motivating.",
  "You are a great example.",
  "You are so admirable.",
  "You are a great achiever.",
  "You are so accomplished.",
  "You are a great winner.",
  "You are so successful.",
  "You are a great champion.",
  "You are so triumphant.",
  "You are a great overcomer.",
  "You are so resilient.",
  "You are a great survivor.",
  "You are so tough.",
  "You are a great fighter.",
  "You are so determined.",
  "You are a great go-getter.",
  "You are so ambitious.",
  "You are a great pursuer.",
  "You are so driven.",
  "You are a great dream chaser.",
  "You are so passionate.",
  "You are a great lover of life.",
  "You are so joyful.",
  "You are a great optimist.",
  "You are so hopeful.",
  "You are a great believer.",
  "You are so faithful.",
  "You are a great friend to animals.",
  "You are so gentle.",
  "You are a great nature lover.",
  "You are so eco-friendly.",
  "You are a great earth protector.",
  "You are so mindful.",
  "You are a great thinker.",
  "You are so reflective.",
  "You are a great philosopher.",
  "You are so deep.",
  "You are a great soul.",
  "You are so spiritual.",
  "You are a great light in the world.",
];
